name: Publish FE
description: Build and deploy webapp
branding:
  icon: package
  color: blue
inputs:
  repo:
    description: 'Repository holding webapp code'
    required: true
  aws-access-key:
    description: 'AWS Secret Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region of the S3 and CloudFront resources'
    required: true
  aws-s3-name:
    description: 'Name of the AWS S3 bucket'
    required: true
  aws-cloudfront-name:
    description: 'Name of the AWS S3 bucket'
    required: true
  slack-channel:
    description: 'Name of the Slack channel used for CI alerts'
    required: true
  slack-token:
    description: 'Token for Slack integration'
    required: true
  build-path:
    description: 'Local path of the build'
    required: true
  node-version:
    description: 'NodeJS required version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Notify Slack Start
        id: notify-slack-start
        uses: cristi-mb/slack-notify@1.1
        with:
          message-type: start
          slack-channel: inputs.slack-channel
          slack-bot-token: inputs.slack-token
